name: Suckless-Odin CI

permissions:
  contents: write
  pull-requests: write

on:
  workflow_dispatch:
  push:
    branches: ["master", "main"]
  pull_request:
    types: [opened, reopened, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint & Codegen
    uses: ./.github/workflows/ci-lint.yml

  linux:
    name: Linux CI
    needs: [lint]
    uses: ./.github/workflows/ci-linux.yml

  windows:
    name: Windows CI
    needs: [lint]
    uses: ./.github/workflows/ci-windows.yml
